### ISSUE TITLE
Error when Compiling

### ISSUE THREAD

**Issue by ZichenMiao** [antigol/obj2voxel#2]
cargo 1.49.0 (d00d64df9 2020-12-05)

error[E0277]: the trait bound `ThreadRng: rand_core::RngCore` is not satisfied                                                                                                                
   --> src/main.rs:362:24                                                                                                                                                                     
    |                                          
362 |             die.sample(&mut rng),
    |                        ^^^^^^^^ the trait `rand_core::RngCore` is not implemented for `ThreadRng`
    |                                          
help: trait impl with same name found
   --> /home/mzc/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.4.2/src/lib.rs:373:1
    |                                          
373 | / impl<'a, R: RngCore + ?Sized> RngCore for &'a mut R {
374 | |     #[inline(always)]
375 | |     fn next_u32(&mut self) -> u32 {
376 | |         (**self).next_u32()
...   |                                        
392 | |     }                                  
393 | | }                                      
    | |_^                                      
    = note: perhaps two different versions of crate `rand_core` are being used?
    = note: required because of the requirements on the impl of `rand::rng::Rng` for `ThreadRng`

**Comment by ZichenMiao** [comment]
Update:

compile successfully with cargo 1.30.0
using the [4ef9dfe](https://github.com/mariogeiger/obj2voxel/tree/4ef9dfefee971408b5136e1e78abf499459f53f2) commit

**Comment by mariogeiger** [comment]
Thanks for the feedback! I updated the dependencies :-)
