### ISSUE TITLE
Failing to compile

### ISSUE THREAD

**Issue by stephenphillips** [antigol/obj2voxel#3]
Trying to compile the latest build, installed Rust and ran the cargo command.
The error, I think, is mismatched types. Unsure how to fix.

`warning: use of deprecated associated function `clap::Arg::<'help>::with_name`: Replaced with `Arg::new`
   --> src\main.rs:203:24
    |
203 |             clap::Arg::with_name("INPUT")
    |                        ^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: use of deprecated associated function `clap::Arg::<'help>::with_name`: Replaced with `Arg::new`
   --> src\main.rs:209:24
    |
209 |             clap::Arg::with_name("OUTPUT")
    |                        ^^^^^^^^^

warning: use of deprecated associated function `clap::Arg::<'help>::with_name`: Replaced with `Arg::new`
   --> src\main.rs:215:24
    |
215 |             clap::Arg::with_name("size")
    |                        ^^^^^^^^^

warning: use of deprecated associated function `clap::Arg::<'help>::with_name`: Replaced with `Arg::new`
   --> src\main.rs:223:24
    |
223 |             clap::Arg::with_name("border")
    |                        ^^^^^^^^^

warning: use of deprecated associated function `clap::Arg::<'help>::with_name`: Replaced with `Arg::new`
   --> src\main.rs:233:24
    |
233 |             clap::Arg::with_name("view")
    |                        ^^^^^^^^^

error[E0308]: mismatched types
   --> src\main.rs:234:24
    |
234 |                 .short("v")
    |                        ^^^ expected `char`, found `&str`

warning: use of deprecated associated function `clap::Arg::<'help>::with_name`: Replaced with `Arg::new`
   --> src\main.rs:239:24
    |
239 |             clap::Arg::with_name("double")
    |                        ^^^^^^^^^

warning: use of deprecated associated function `clap::Arg::<'help>::with_name`: Replaced with `Arg::new`
   --> src\main.rs:244:24
    |
244 |             clap::Arg::with_name("rotate")
    |                        ^^^^^^^^^

warning: use of deprecated associated function `clap::Arg::<'help>::with_name`: Replaced with `Arg::new`
   --> src\main.rs:249:24
    |
249 |             clap::Arg::with_name("alpha_rot")
    |                        ^^^^^^^^^

warning: use of deprecated associated function `clap::Arg::<'help>::with_name`: Replaced with `Arg::new`
   --> src\main.rs:257:24
    |
257 |             clap::Arg::with_name("beta_rot")
    |                        ^^^^^^^^^

warning: use of deprecated associated function `clap::Arg::<'help>::with_name`: Replaced with `Arg::new`
   --> src\main.rs:265:24
    |
265 |             clap::Arg::with_name("gamma_rot")
    |                        ^^^^^^^^^

warning: use of deprecated associated function `clap::Arg::<'help>::with_name`: Replaced with `Arg::new`
   --> src\main.rs:273:24
    |
273 |             clap::Arg::with_name("diagonal_bounding_box_xy")
    |                        ^^^^^^^^^

warning: use of deprecated associated function `clap::Arg::<'help>::with_name`: Replaced with `Arg::new`
   --> src\main.rs:280:24
    |
280 |             clap::Arg::with_name("diagonal_bounding_box")
    |                        ^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
warning: `obj2voxel` (bin "obj2voxel") generated 12 warnings
error: failed to compile `obj2voxel v0.2.4 (https://github.com/mariogeiger/obj2voxel#a6f1e375)``

**Comment by mariogeiger** [comment]
Surprising. I thought that `Cargo.lock` would lock all dep versions

**Comment by mariogeiger** [comment]
I will do a `cargo update` and let see if it helps

**Comment by mariogeiger** [comment]
Did you remove `Cargo.lock` or run `cargo update` ?
I ran `cargo update` and fixed the issues

**Comment by nanogram** [comment]
Welp, now it installs correctly, ty.

**Comment by stephenphillips** [comment]
Now it works, thank you.
